version: '3.8'

services:
  mysql:
    image: mysql:latest
    container_name: mysql_server
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: mydatabase
      MYSQL_USER: 1    #user to login web url
      MYSQL_PASSWORD: 1   #password to login web url
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: phpmyadmin
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: rootpassword
    ports:
      - "4100:80" #"8000:80"
    depends_on:
      - mysql

  php:
    build: .
    container_name: php_server
    volumes:
      - ./www:/var/www/html
    ports:
      - "80:80"  #localport : containerport
    depends_on:
      - mysql

volumes:
  mysql_data: